[".local/share/antidote"]
    type = "archive"
    url = "https://github.com/mattmc3/antidote/archive/main.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".config/nvim"]
    type = "git-repo"
    url = "git@github.com:LazyVim/starter.git"
    refreshPeriod = "168h"
