format = "$character$directory$all"
add_newline = false
command_timeout = 5000

[aws]
disabled = true

[bun]
symbol = " "

[character]
success_symbol = "[](bold cyan)"
error_symbol = "[](bold red)"
vimcmd_symbol = "[](bold green)"

[deno]
style = "bold black"
symbol = " "

[directory]
style = "bold white"

[docker_context]
disabled = false

[git_branch]
style = "bold yellow"

[hostname]
ssh_only = true
format = "[$ssh_symbol$hostname]($style) "

[mise]
disabled = true

[nodejs]
detect_extensions = []
detect_files = ["package-lock.json", "yarn.lock", "pnpm-lock.yaml", ".node-version", ".nvmrc"]
detect_folders = []
